import pandas as pd

image=config['image']
workdir: config['workdir']
output_path=config['output_path']
data_path=config['data_path']
sources=config['sources']

run_wildcards=config.get('run_wildcards'], '')

# rule that creates dataframe and puts it in data path
rule make_dataframe:
    output:
        '%s/simple_df.pq' % data_path
    run:
        first_row = [1] * 10
        second_row = [2] * 10
        third_row = [3] * 10
        col_names = ['col'+i for i in range(10)]
        row_index = ['ones', 'twos', 'threes']
        data = [first_row, second_row, third_row]
        df = pd.DataFrame(data, columns=col_names, index=row_index)
        df.to_parquet(output)

# rule that runs multiply from transform
rule transform_dataframe:
    input:
        '%s/simple_df.pq' % data_path
    output:
        '{output_path}/%s/transformed.tsv' % run_wildcards
    log:
        '{output_path}/%s/log/transform_dataframe.log' % run_wildcards
    params:
        FINAL='transformed.tsv'
    shell:
        'python3 examples/simple/transform.py'
        ' --input-path {input}'
        ' --output-path {output}'
        ' --multiplier {wildcards.multiply}'
        ' --{wildcards.sqrt_opt}'
        ' &>{log}'

# rule that uses shell command to filter lines by id
#rule filter_transformed:
#    input:
#        '{output_path}/%s/transformed.tsv' % run_wildcards
#    output:
#        '{output_path}/%s/filtered.tsv' % run_wilcards
#    params:
#        FINAL='filtered.tsv'
#    shell:
#        '
